services:
  couchdb:
    image: couchdb:latest
    container_name: kidsapp-couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USERNAME}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - couchdb_data:/opt/couchdb/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: kidsapp-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: ./apps/backend
      dockerfile: ./dockerfile
    container_name: kidsapp-backend
    ports:
      - "5000:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_URL=${BROKER_URI}
      - AMQP_QUEUE_PREFIX=${AMQP_QUEUE_PREFIX}
      - COUCHDB_PROTOCOL=${COUCHDB_PROTOCOL}
      - COUCHDB_HOST=couchdb
      - COUCHDB_PORT=${COUCHDB_PORT}
      - COUCHDB_USERNAME=${COUCHDB_USERNAME}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_DATABASE=${COUCHDB_DATABASE}
      - BACKEND_PORT=5000
    depends_on:
      rabbitmq:
        condition: service_started
      couchdb:
        condition: service_started

  bff:
    build:
      dockerfile: ./docker/nest.dockerfile
      args:
        APP: bff
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RABBITMQ_URL=${BROKER_URI}
      - AMQP_QUEUE_PREFIX=${AMQP_QUEUE_PREFIX}
    depends_on:
      backend:
        condition: service_started

  frontend:
    build:
      dockerfile: ./docker/angular.dockerfile
      args:
        APP: frontend
    depends_on:
      - bff
    environment:
      - BASE_URL=http://localhost:3000/api
    ports:
      - "8080:8080"

volumes:
  couchdb_data:
    driver: local